project:
  type: book

book:
  title: "Métodos analíticos"
  author: "Felipe González"
  chapters:
    - index.qmd
    - 01-introduccion.qmd
    - 02-flujo-basico.qmd
    - 02-flujo-basico-2.qmd
    - 03-modelos-genericos.qmd
    - 05-dags.qmd
    - 06-calculo-do.qmd
    - 07-buenos-malos-controles.qmd
    - 08-mcmc.qmd
bibliography: referencias/book.bib

format:
  html:
    theme: journal
    lang: es
    font-size: 1.1em
    code-fold: false



